services:
  flamma-db:
    build:
      dockerfile: docker/postgres.Dockerfile
      context: .
    image: postgres.local:18
    container_name: flamma-db
    restart: no
    hostname: dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_flamma
    ports:
      - '5432:5432'
    volumes:
      - flamma-db:/var/lib/postgresql
    networks:
      - dev-flamma
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready --quiet --username=postgres --dbname=postgres || exit 1']
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 15s

  flamma-redis:
    build:
      dockerfile: docker/redis.Dockerfile
      context: .
    image: redis.local:8
    container_name: flamma-redis
    restart: no
    hostname: dev
    ports:
      - '6379:6379'
    networks:
      - dev-flamma
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli --raw incr ping || exit 1']
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 15s

  flamma-mailpit:
    build:
      dockerfile: docker/mailpit.Dockerfile
      context: .
    image: mailpit.local:1
    container_name: flamma-mailpit
    restart: no
    hostname: dev
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - dev-flamma
    healthcheck:
      test: ['CMD', '/mailpit', 'readyz']
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 10s

  flamma-minio:
    image: minio/minio:latest
    container_name: flamma-minio
    restart: no
    hostname: dev
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      TZ: America/Sao_Paulo
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    volumes:
      - flamma-minio:/data
    networks:
      - dev-flamma
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 10s

volumes:
  flamma-db:
    name: flamma-db
  flamma-minio:
    name: flamma-minio

networks:
  dev-flamma:
    name: dev-flamma
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dev-flamma
      com.docker.network.bridge.host_binding_ipv4: '127.0.0.1'
