<?php

declare(strict_types=1);

return [
    'appointments' => [
        'infolist' => [
            'tabs' => [
                'consultation' => 'Consultation',
                'client' => 'Client',
                'prontuario' => 'Financial Profile',
            ],
            'consultation' => 'Consultation Details',
            'client' => 'About the Client',
            'client_email' => 'Email',
            'financial_profile' => 'Financial Profile',
            'financial_profile_description' => 'Profile filled in by the client before the consultation.',
            'no_anamnese' => 'Profile not filled in',
            'no_anamnese_description' => 'This client has not filled in their financial profile yet.',
            'meeting_url_pending' => 'Awaiting confirmation',
        ],
    ],
    'documents' => [
        'navigation_label' => 'Materials',
        'model_label' => 'Material',
        'plural_model_label' => 'Materials',
        'table' => [
            'title' => 'Document Title',
            'extension_type' => 'Type',
            'active' => 'Is Active',
        ],
        'form' => [
            'title' => 'Document Title',
            'extension_type' => 'Extension',
            'link' => 'Link',
            'active' => 'Is Active',
            'heading' => 'New Document',
            'files' => 'File',
            'tab_file' => 'File',
            'tab_link' => 'Link',
            'type_hint' => 'Upload a file OR set a link. If both are provided, the file takes priority and the link will be discarded.',
        ],
    ],
    'share_documents' => [
        'action' => [
            'label' => 'Share',
            'heading' => 'Share Document',
            'modal_description' => 'Only customers that do not have access to this document will be listed.',
            'form' => [
                'customer' => 'Customer',
            ],
        ],
        'relation_manager' => [
            'title' => 'Shared With',
            'table' => [
                'employee' => 'Employee',
                'shared_at' => 'Shared At',
                'active' => 'Active',
            ],
            'actions' => [
                'deactivate' => 'Deactivate',
                'activate' => 'Activate',
            ],
        ],
    ],
    'appointment_records' => [
        'previous_summary' => [
            'label' => 'Previous appointment summary',
            'modal_heading' => 'Last appointment summary for this client',
            'modal_description' => 'Internal note generated by AI in the latest published appointment. Use it to prepare before the session.',
            'close' => 'Close',
            'empty' => 'This client has no previous appointment summary available yet.',
            'last_appointment_on' => 'Last appointment on :date',
        ],
        'create' => [
            'label' => 'Create Record',
            'modal_heading' => 'Create Record',
            'modal_description' => 'Upload the consultation document. AI will generate a draft for you to review.',
            'submit' => 'Send for analysis',
            'form' => [
                'document' => 'Document (PDF, DOC or DOCX)',
                'document_helper' => 'Max size: 10 MB.',
            ],
            'started' => [
                'title' => 'Generation started',
                'body' => 'You will be notified when the record is ready for review.',
            ],
        ],
        'review' => [
            'label_view' => 'View Record',
            'label_review' => 'Review Record',
            'submit_save' => 'Save changes',
            'submit_publish' => 'Publish to client',
            'save_draft' => 'Save draft',
        ],
    ],
];
