<?php

namespace TresPontosTech\Billing\Core;

use Illuminate\Support\Manager;
use TresPontosTech\Billing\Barte\BarteAdapter;
use TresPontosTech\Billing\Barte\BarteClient;
use TresPontosTech\Billing\Core\Contracts\BillingContract;
use TresPontosTech\Billing\Core\Enums\BillingProviderEnum;
use TresPontosTech\Billing\Stripe\Subscription\StripeAdapter;

class BillingManager extends Manager
{
    public function getDefaultDriver(): BillingContract
    {
        return $this->barteDriver();
    }

    public function stripeDriver(): BillingContract
    {
        return new StripeAdapter;
    }

    private function barteDriver(): BillingContract
    {
        return new BarteAdapter(new BarteClient);
    }

    public function getDriver(BillingProviderEnum $driver = BillingProviderEnum::Stripe): BillingContract
    {
        return match ($driver) {
            BillingProviderEnum::Stripe => $this->stripeDriver(),
            BillingProviderEnum::Barte => $this->barteDriver(),
            BillingProviderEnum::Contractual => throw new \Exception('To be implemented'),
        };
    }

    public function getDrivers()
    {
        return parent::getDrivers(); // TODO: Change the autogenerated stub
    }
}
