<?php

namespace TresPontosTech\Billing\Core;

use Illuminate\Support\Manager;
use TresPontosTech\Billing\Core\Contracts\BillingContract;
use TresPontosTech\Billing\Core\Enums\BillingProviderEnum;
use TresPontosTech\Billing\Stripe\Subscription\StripeAdapter;

final class BillingManager extends Manager
{
    public function getDefaultDriver(): BillingContract
    {
        return new StripeAdapter;
    }

    public function stripeDriver(): BillingContract
    {
        return new StripeAdapter;
    }

    public function getDriver(BillingProviderEnum $driver = BillingProviderEnum::Stripe): BillingContract
    {
        return match ($driver) {
            BillingProviderEnum::Stripe => $this->stripeDriver(),
            BillingProviderEnum::Contractual => throw new \Exception('To be implemented'),
        };
    }

    public function getDrivers()
    {
        return parent::getDrivers(); // TODO: Change the autogenerated stub
    }
}
