<?php

declare(strict_types=1);

namespace TresPontosTech\PanelCompany\DTOs;

final readonly class CategorySlice
{
    /**
     * @param  string  $color  Semantic colour token mapped to literal classes in the view
     * @param  string  $path  SVG donut slice path `d` (generated by the home widget; empty for raw data)
     */
    public function __construct(
        public string $label,
        public int $value,
        public float $percent,
        public string $color,
        public string $path = '',
    ) {}
}
