<?php

declare(strict_types=1);

namespace TresPontosTech\PanelCompany\DTOs;

final readonly class CreditKpi
{
    /**
     * @param  string  $tone  Semantic colour token mapped to literal classes in the view: primary|success|info|neutral
     * @param  string  $sparkline  SVG polyline points (generated by the home widget; empty for raw data)
     */
    public function __construct(
        public string $label,
        public int $value,
        public string $caption,
        public string $tone,
        public string $sparkline = '',
    ) {}
}
